select * from employees;

-- 1. FIND OUT COUNTRY NAME AND REGION NAME FROM COUNTRIES AND REGION TABLE
select COUNTRY_NAME, REGION_NAME from COUNTRIES
inner join REGIONS
on COUNTRIES.REGION_ID = REGIONS.REGION_ID;

-- 2. FIND OUT FIRST_NAME AND JOB_TITLE FROM JOBS AND EMPLOYEES TABLE
select FIRST_NAME, JOB_TITLE from EMPLOYEES
inner join JOBS
on EMPLOYEES.JOB_ID = JOBS.JOB_ID;

-- 3. FIND OUT DEPARTMENT_NAME AND CITY
select DEPARTMENT_NAME, CITY from DEPARTMENTS
inner join LOCATIONS
on DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID;

-- 4. FIND OUT ALL CITIES  AND COUNTRY NAMES
select city,COUNTRY_NAME from LOCATIONS
inner join COUNTRIES
on LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID;

-- 5. FIND OUT FIRST_NAME, LAST NAME, DEPARTMENT ID , DEPARTMENT NAME  FOR  DEPARTMENT ID 80 OR 40
select FIRST_NAME,LAST_NAME,EMPLOYEES.DEPARTMENT_ID,DEPARTMENT_NAME from EMPLOYEES
inner join DEPARTMENTS
on EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
where EMPLOYEES.DEPARTMENT_ID in (80,40);

-- 6. FIND OUT CITY , COUNTRY_NAME OF THAT CITY , REGION_NAME OF THAT CITY
select city,COUNTRY_NAME,REGION_NAME from LOCATIONS
inner join COUNTRIES
on LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
inner join REGIONS
on COUNTRIES.REGION_ID = REGIONS.REGION_ID;

-- 7. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY
select FIRST_NAME,JOB_TITLE,DEPARTMENT_NAME,CITY from EMPLOYEES
inner join JOBS J on EMPLOYEES.JOB_ID = J.JOB_ID
inner join DEPARTMENTS D on EMPLOYEES.DEPARTMENT_ID = D.DEPARTMENT_ID
inner join LOCATIONS L on D.LOCATION_ID = L.LOCATION_ID;

-- 8. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY , COUNTRY_NAME , REGION_NAME
select e.first_name , j.job_title , d.department_name,
       l.city , c.country_name , r.region_name
from employees e
         inner join jobs j    on   e.job_id = j.job_id
         inner join departments d on e.department_id = d.department_id
         inner join locations l on l.location_id = d.location_id
         inner join countries c on l.country_id = c.country_id
         inner join regions r on r.region_id = c.region_id;

--9. FIND OUR  EMPLOYEES FIRST_NAME, LAST NAME, DEPARTMENT ID AND ALL DEPARTMENTS
--  INCLUDING  WHERE DO NOT HAVE ANY EMPLOYEE.
select FIRST_NAME,LAST_NAME,DEPARTMENTS.DEPARTMENT_ID,DEPARTMENT_NAME from DEPARTMENTS
left join EMPLOYEES
on DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID;

--10. FIND OUT ALL DEPARTMENT_NAME  , LOCATION_ID , AND COUNTRY_ID
-- INCLUDING THOSE LOCATIONS  WITH NO DEPARTMENT
select DEPARTMENT_NAME,departments.LOCATION_ID,COUNTRY_ID from DEPARTMENTS
right join LOCATIONS
on DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
order by 1;

--11.FIND OUT DEPARTMENT_NAME , LOCATION_ID , AND COUNTRY_NAME
-- INCLUDING THOSE COUNTRIES WITH NO DEPARTMENT
select DEPARTMENT_NAME,DEPARTMENTS.LOCATION_ID,COUNTRY_NAME from DEPARTMENTS
right join LOCATIONS
on DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
right join COUNTRIES
on LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
order by 1;

--12. FIND OUT EMPLOYEES FIRST_NAME, DEPARTMENT ID AND DEPARTMENT NAME
-- INCLUDING THOSE DOES NOT HAVE DEPARTMENT
-- INCLUDING THOSE DEPARTMENTS  DOES NOT HAVE ANY MATCHING EMPLOYEES
select FIRST_NAME, EMPLOYEES.DEPARTMENT_ID,DEPARTMENT_NAME from DEPARTMENTS
full join EMPLOYEES
on DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID;